/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRegistrationsRouteImport } from './routes/dashboard.registrations'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSheetsRouteImport } from './routes/dashboard.sheets'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as OrganizersIdRouteImport } from './routes/organizers.$id'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard.events.index'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as EventsIdRegisterRouteImport } from './routes/events.$id.register'
import { Route as EventsIdSuccessRouteImport } from './routes/events.$id.success'
import { Route as DashboardEventsIdEditRouteImport } from './routes/dashboard.events.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationsRoute = DashboardRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSheetsRoute = DashboardSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersIdRoute = OrganizersIdRouteImport.update({
  id: '/organizers/$id',
  path: '/organizers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsIdRegisterRoute = EventsIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdSuccessRoute = EventsIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => EventsIdRoute,
} as any)
const DashboardEventsIdEditRoute = DashboardEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sheets': typeof DashboardSheetsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/organizers/$id': typeof OrganizersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
  '/events/$id/success': typeof EventsIdSuccessRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sheets': typeof DashboardSheetsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/organizers/$id': typeof OrganizersIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
  '/events/$id/success': typeof EventsIdSuccessRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sheets': typeof DashboardSheetsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/organizers/$id': typeof OrganizersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
  '/events/$id/success': typeof EventsIdSuccessRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/users'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/events/$id'
    | '/organizers/$id'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/events/new'
    | '/events/$id/register'
    | '/events/$id/success'
    | '/dashboard/events/'
    | '/dashboard/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/users'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/events/$id'
    | '/organizers/$id'
    | '/admin'
    | '/dashboard'
    | '/dashboard/events/new'
    | '/events/$id/register'
    | '/events/$id/success'
    | '/dashboard/events'
    | '/dashboard/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/users'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/events/$id'
    | '/organizers/$id'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/events/new'
    | '/events/$id/register'
    | '/events/$id/success'
    | '/dashboard/events/'
    | '/dashboard/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EventsIdRoute: typeof EventsIdRouteWithChildren
  OrganizersIdRoute: typeof OrganizersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrations': {
      id: '/dashboard/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof DashboardRegistrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sheets': {
      id: '/dashboard/sheets'
      path: '/sheets'
      fullPath: '/dashboard/sheets'
      preLoaderRoute: typeof DashboardSheetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers/$id': {
      id: '/organizers/$id'
      path: '/organizers/$id'
      fullPath: '/organizers/$id'
      preLoaderRoute: typeof OrganizersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$id/register': {
      id: '/events/$id/register'
      path: '/register'
      fullPath: '/events/$id/register'
      preLoaderRoute: typeof EventsIdRegisterRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/success': {
      id: '/events/$id/success'
      path: '/success'
      fullPath: '/events/$id/success'
      preLoaderRoute: typeof EventsIdSuccessRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/dashboard/events/$id/edit': {
      id: '/dashboard/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/dashboard/events/$id/edit'
      preLoaderRoute: typeof DashboardEventsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardRegistrationsRoute: typeof DashboardRegistrationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSheetsRoute: typeof DashboardSheetsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardEventsIdEditRoute: typeof DashboardEventsIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRegistrationsRoute: DashboardRegistrationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSheetsRoute: DashboardSheetsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardEventsIdEditRoute: DashboardEventsIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsIdRouteChildren {
  EventsIdRegisterRoute: typeof EventsIdRegisterRoute
  EventsIdSuccessRoute: typeof EventsIdSuccessRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdRegisterRoute: EventsIdRegisterRoute,
  EventsIdSuccessRoute: EventsIdSuccessRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EventsIdRoute: EventsIdRouteWithChildren,
  OrganizersIdRoute: OrganizersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
